/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markcalculator;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class StudentInformation extends javax.swing.JDialog {

    /**
     * Creates new form StudentInformation
     */
    public StudentInformation() {
       
        initComponents();
    }

    private StudentInformation(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Student Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel4.setText("Student Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Student Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 140, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, 30));

        jTextField4.setToolTipText("");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 30));

        jLabel6.setText("Mark");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 30, -1));

        jLabel7.setText("Mark");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel8.setText("Mark");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel9.setText("Mark");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel10.setText("Mark");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 160, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 160, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 160, 30));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 160, 30));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 160, 30));

        jButton1.setText("Max Mark");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jButton2.setText("Min Mark");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jButton3.setText("Avg Mark");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jLabel11.setText("Result");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 240, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       float num1,num2,num3,num4,num5;
        try{
          num1=Integer.parseInt(
      this.jTextField6.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
    return;
     }
     
      try{
           num2=Integer.parseInt(
      this.jTextField7.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        try{
           num3=Integer.parseInt(
      this.jTextField8.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        
            try{
           num4=Integer.parseInt(
      this.jTextField9.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     }
            
        try{
           num5=Integer.parseInt(
      this.jTextField10.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     }       
            float sum= num1 + num2 +num3 + num4+ num5;
            float AvgResult=sum/5;
            
            this.jTextField11.setText(" AVG Result: "+ AvgResult);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String nam1=this.jTextField1.getText();
        String nam2=this.jTextField2.getText();
        String nam3=this.jTextField3.getText();
        String nam4=this.jTextField4.getText();
        String nam5=this.jTextField5.getText();
        float num1,num2,num3,num4,num5;
        try{
          num1=Integer.parseInt(
      this.jTextField6.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
    return;
     }
     
      try{
           num2=Integer.parseInt(
      this.jTextField7.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        try{
           num3=Integer.parseInt(
      this.jTextField8.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        
            try{
           num4=Integer.parseInt(
      this.jTextField9.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     }
            
        try{
           num5=Integer.parseInt(
      this.jTextField10.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        int st=5;
        switch(st){
            case 1:
            if(num1>num2){
            if(num1>num3){
                if(num1>num4){
                    if(num1>num5){
                        this.jTextField11.setText(" Student Name: "+ nam1 +" Mark: "+ num1);
                    }
                }
                
            }
}
             break;
             case 2:
            if(num2>num1){
            if(num2>num3){
                if(num2>num4){
                    if(num2>num5){
                        this.jTextField11.setText(" Student Name: "+ nam2 +" Mark: "+ num2);
                    }
                }
                
            }
}
              break;
                      case 3:
            if(num3>num1){
            if(num3>num2){
                if(num3>num4){
                    if(num3>num5){
                        this.jTextField11.setText(" Student Name: "+ nam3 +" Mark: "+ num3);
                    }
                }
                
            }
}
              break;
                 
                 case 4:
            if(num4>num1){
            if(num4>num2){
                if(num4>num3){
                    if(num4>num5){
                        this.jTextField11.setText(" Student Name: "+nam4 +" Mark: "+ num4);
                    }
                }
                
            }
}
              break;
                          case 5:
            if(num5>num1){
            if(num5>num2){
                if(num5>num3){
                    if(num5>num4){
                        this.jTextField11.setText(" Student Name: "+ nam5 +" Mark: "+ num5);
                    }
                }
                
            }
}
              break;
            
            
            
            
        }
        
       
            
            
            
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
         String nam1=this.jTextField1.getText();
        String nam2=this.jTextField2.getText();
        String nam3=this.jTextField3.getText();
        String nam4=this.jTextField4.getText();
        String nam5=this.jTextField5.getText();
        float num1,num2,num3,num4,num5;
        try{
          num1=Integer.parseInt(
      this.jTextField6.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
    return;
     }
     
      try{
           num2=Integer.parseInt(
      this.jTextField7.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        try{
           num3=Integer.parseInt(
      this.jTextField8.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        
            try{
           num4=Integer.parseInt(
      this.jTextField9.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     }
            
        try{
           num5=Integer.parseInt(
      this.jTextField10.getText()
      );
     }catch(Exception e){
     JOptionPane.showMessageDialog(this, "this input is not number", "error", JOptionPane.ERROR_MESSAGE);
      return;
     } 
        int st=5;
        switch(st){
            case 1:
            if(num1<num2){
            if(num1<num3){
                if(num1<num4){
                    if(num1<num5){
                        this.jTextField11.setText(" Student Name: "+ nam1 +" Mark: "+ num1);
                    }
                }
                
            }
}
             break;
             case 2:
            if(num2<num1){
            if(num2<num3){
                if(num2<num4){
                    if(num2<num5){
                        this.jTextField11.setText(" Student Name: "+ nam2 +" Mark: "+ num2);
                    }
                }
                
            }
}
              break;
                      case 3:
            if(num3<num1){
            if(num3<num2){
                if(num3<num4){
                    if(num3<num5){
                        this.jTextField11.setText(" Student Name: "+ nam3 +" Mark: "+ num3);
                    }
                }
                
            }
}
              break;
                 
                 case 4:
            if(num4<num1){
            if(num4<num2){
                if(num4<num3){
                    if(num4<num5){
                        this.jTextField11.setText(" Student Name: "+nam4 +" Mark: "+ num4);
                    }
                }
                
            }
}
              break;
                          case 5:
            if(num5<num1){
            if(num5<num2){
                if(num5<num3){
                    if(num5<num4){
                        this.jTextField11.setText(" Student Name: "+ nam5 +" Mark: "+ num5);
                    }
                }
                
            }
}
              break;
            
            
            
            
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentInformation dialog = new StudentInformation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
